FROM elixir:latest

WORKDIR /app

ADD . /app

ARG CRYPTOKNIGHT_DEV_BOT_NAME
ARG CRYPTOKNIGHT_DEV_BOT_TOKEN

RUN mix local.hex --force &&\
    mix local.rebar --force &&\
    mix deps.get &&\
    mix deps.compile

RUN CRYPTOKNIGHT_DEV_BOT_NAM=${CRYPTOKNIGHT_DEV_BOT_NAME} \
    CRYPTOKNIGHT_DEV_BOT_TOKEN=${CRYPTOKNIGHT_DEV_BOT_TOKEN} \
    mix compile
