#!/bin/sh

export CRYPTOKNIGHT_BOT_NAME=${CRYPTOKNIGHT_BOT_NAME}
export CRYPTOKNIGHT_BOT_TOKEN=${CRYPTOKNIGHT_BOT_TOKEN}
export CRYPTOKNIGHT_DEV_BOT_NAME=${CRYPTOKNIGHT_DEV_BOT_NAME}
export CRYPTOKNIGHT_DEV_BOT_TOKEN=${CRYPTOKNIGHT_DEV_BOT_TOKEN}
